<?php

define("TBL_ADMIN_USER","admin_users");
define("TBL_CATEGORY","categories");
define("TBL_CATEGORY_LNG","categories_lng");
define("TBL_CONFIG_VARS","config_vars");
define("TBL_LANGUAGES","languages");
define("TBL_LANGUAGES_TEXTS","language_texts");
define("TBL_LANGUAGES_VAR","language_var");
define("TBL_PRODUCTS","products");
define("TBL_PRODUCTS_LNG","products_lng");
define("TBL_USERS","users");
define("TBL_COMMENTS","comments");
define("TBL_PROMPTS","prompts");
define("TBL_PHOTO","photo");
define("TBL_TAG","tags");
define("TBL_GCM_USERS","gcm_users");
define("TBL_SETTINGS","settings");
define("TBL_PRODUCT_CATEGORY","product_category");
define("TBL_USER_GREETINGS","user_greetings");
define("TBL_ADMIN_GREETINGS","admin_greetings");
?>